# Generated by Django 6.0 on 2026-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_menu1_item_name_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu1',
            name='category',
            field=models.CharField(choices=[('veg', 'vegetable'), ('Chicken', 'Chicken')], default='', max_length=20),
        ),
    ]
