# Generated by Django 6.0 on 2026-01-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_orderitem_cart_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu1',
            name='category',
            field=models.CharField(choices=[('veg', 'vegetable'), ('Chicken', 'Chicken')], default='', max_length=20),
        ),
    ]
