# Generated by Django 6.0 on 2026-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu1',
            name='discription',
            field=models.CharField(default='', max_length=50),
        ),
    ]
