# Generated by Django 6.0 on 2026-01-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_menu1_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='item',
            new_name='product',
        ),
    ]
