# Generated by Django 6.0 on 2026-01-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_item_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu1',
            old_name='discription',
            new_name='description',
        ),
    ]
