# Generated by Django 6.0 on 2026-02-10 05:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_menu1_created_by_menu1_updated_at_menu1_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
