# Generated by Django 6.0 on 2026-02-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_deliveryboy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboy',
            old_name='passworld',
            new_name='password',
        ),
    ]
