# Generated by Django 6.0 on 2026-03-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_order_txnid_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu1',
            name='category',
            field=models.CharField(choices=[('veg', 'vegetable'), ('Chicken', 'Chicken'), ('South Indian', 'South Indian')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
